name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: dart-test-2022/arithmetic_test
          token: ${{secrets.TEST_KEY}}
          path: test
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - run: dart test --file-reporter json:tests.json
      - run: python confest.py
      - run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}) 
          python test/sendtest.py ${{github.actor}} '${{github.repository}}' "$CHANGED_FILES"
